<?php

declare(strict_types=1);

namespace FahimTayebee\Preflight\Reporters;

use FahimTayebee\Preflight\Core\AuditResult;
use FahimTayebee\Preflight\Core\Severity;
use FahimTayebee\Preflight\Reporters\Contracts\ReporterInterface;

final class HtmlReporter implements ReporterInterface
{
    /**
     * @param array<string, mixed> $report
     */
    public function render(array $report): string
    {
        $title = 'Preflight Laravel Project Audit Report';

        return '<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>' . $this->e($title) . '</title>
<style>' . $this->css() . '</style>
</head>
<body>
<div class="page">
<header class="hero">
<div>
<p class="eyebrow">Preflight</p>
<h1>Laravel Project Audit Report</h1>
<p class="muted">Generated at ' . $this->e($report['meta']['generated_at'] ?? 'unknown') . '</p>
</div>
<div class="meta">
<div><span>Project</span><strong>' . $this->e($report['meta']['project_path'] ?? 'unknown') . '</strong></div>
<div><span>Package</span><strong>' . $this->e($report['meta']['package'] ?? 'Preflight') . ' ' . $this->e($report['meta']['version'] ?? '') . '</strong></div>
<div><span>PHP</span><strong>' . $this->e($report['meta']['php_version'] ?? PHP_VERSION) . '</strong></div>
<div><span>Laravel</span><strong>' . $this->e($report['meta']['laravel_version'] ?? 'unknown') . '</strong></div>
</div>
</header>
' . $this->renderSummary($report) . '
' . $this->renderBaseline($report) . '
' . $this->renderChangedFiles($report) . '
' . $this->renderScannerTiming($report) . '
' . $this->renderIssues($report) . '
<footer>Generated by <strong>Preflight</strong>. <a href="https://github.com/ftayebee/preflight">github.com/ftayebee/preflight</a></footer>
</div>
</body>
</html>';
    }

    public function e(mixed $value): string
    {
        return htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }

    public function badge(string $label, string $type): string
    {
        return '<span class="badge badge-' . $this->e(strtolower($type)) . '">' . $this->e($label) . '</span>';
    }

    public function formatFile(?string $file, ?int $line): string
    {
        if ($file === null || $file === '') {
            return 'n/a';
        }

        return $line === null ? $file : $file . ':' . $line;
    }

    /**
     * @param array<string, mixed> $report
     */
    public function renderSummary(array $report): string
    {
        $score = (int) ($report['score'] ?? 100);
        $status = $score >= 80 ? 'Passed' : ($score >= 60 ? 'Warning' : 'Failed');
        $counts = (array) ($report['counts'] ?? []);
        $confidence = (array) ($report['confidence_counts'] ?? []);
        $cards = [
            ['Score', $score . '/100', strtolower($status)],
            ['Status', $status, strtolower($status)],
            ['Total issues', (string) ($report['total_issues'] ?? 0), 'neutral'],
            ['Visible issues', (string) ($report['visible_issues'] ?? $report['total_issues'] ?? 0), 'neutral'],
            ['Critical', (string) ($counts['critical'] ?? 0), 'critical'],
            ['High', (string) ($counts['high'] ?? 0), 'high'],
            ['Medium', (string) ($counts['medium'] ?? 0), 'medium'],
            ['Low', (string) ($counts['low'] ?? 0), 'low'],
            ['Info', (string) ($counts['info'] ?? 0), 'info'],
        ];
        $html = '<section class="grid cards">';

        foreach ($cards as [$label, $value, $type]) {
            $html .= '<article class="card card-' . $this->e($type) . '"><span>' . $this->e($label) . '</span><strong>' . $this->e($value) . '</strong></article>';
        }

        $html .= '</section><section class="grid two"><article class="panel"><h2>Confidence</h2><div class="stack">';
        foreach (['high', 'medium', 'low'] as $level) {
            $html .= '<div class="row"><span>' . ucfirst($level) . '</span><strong>' . $this->e($confidence[$level] ?? 0) . '</strong></div>';
        }
        $html .= '</div></article><article class="panel"><h2>Enabled Scanners</h2><p>' . $this->e(implode(', ', (array) ($report['meta']['enabled_scanners'] ?? [])) ?: 'none') . '</p></article></section>';

        return $html;
    }

    /**
     * @param array<string, mixed> $report
     */
    public function renderIssues(array $report): string
    {
        $issues = array_values(array_filter((array) ($report['results'] ?? []), static fn (mixed $item): bool => $item instanceof AuditResult));
        $html = '<section class="panel"><div class="section-title"><h2>Issues</h2><span>' . count($issues) . ' visible</span></div>';

        if ($issues === []) {
            return $html . '<p class="muted">No visible issues.</p></section>';
        }

        $html .= '<div class="table-wrap"><table><thead><tr><th>Severity</th><th>Confidence</th><th>Code</th><th>Scanner</th><th>Title</th><th>File</th><th>Recommendation</th></tr></thead><tbody>';

        foreach ($issues as $issue) {
            $html .= '<tr><td>' . $this->badge($issue->severity->value, $issue->severity->value) . '</td><td>' . $this->badge($issue->confidence, $issue->confidence) . '</td><td><code>' . $this->e($issue->code) . '</code></td><td>' . $this->e($issue->scanner) . '</td><td>' . $this->e($issue->title) . '</td><td>' . $this->e($this->formatFile($issue->file, $issue->line)) . '</td><td>' . $this->e($issue->recommendation ?? '') . '</td></tr>';
        }

        $html .= '</tbody></table></div><div class="details-list">';

        foreach ($issues as $index => $issue) {
            $html .= $this->renderIssue($issue->toArray(), $index + 1);
        }

        return $html . '</div></section>';
    }

    /**
     * @param array<string, mixed> $issue
     */
    public function renderIssue(array $issue, int $index): string
    {
        $metadata = is_array($issue['metadata'] ?? null) ? $issue['metadata'] : [];
        $html = '<details class="issue"><summary>' . $this->e($index . '. ' . ($issue['title'] ?? 'Issue')) . ' ' . $this->badge((string) ($issue['severity'] ?? 'info'), (string) ($issue['severity'] ?? 'info')) . '</summary>';
        $html .= '<dl>';
        foreach ([
            'Message' => $issue['message'] ?? null,
            'File' => $this->formatFile($issue['file'] ?? null, $issue['line'] ?? null),
            'Recommendation' => $issue['recommendation'] ?? null,
            'Impact' => $metadata['impact'] ?? null,
            'False-positive guidance' => $metadata['false_positive_guidance'] ?? null,
            'Docs URL' => $metadata['docs_url'] ?? null,
        ] as $label => $value) {
            if ($value === null || $value === '') {
                continue;
            }
            $html .= '<dt>' . $this->e($label) . '</dt><dd>' . $this->e($value) . '</dd>';
        }
        $html .= '</dl>';

        foreach (['fix_example_bad' => 'Bad example', 'fix_example_good' => 'Better example'] as $key => $label) {
            if (is_string($metadata[$key] ?? null) && $metadata[$key] !== '') {
                $html .= '<h3>' . $this->e($label) . '</h3><pre><code>' . $this->e($metadata[$key]) . '</code></pre>';
            }
        }

        if (($issue['metadata'] ?? []) !== []) {
            $html .= '<h3>Metadata</h3><pre><code>' . $this->e(json_encode($issue['metadata'], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)) . '</code></pre>';
        }

        return $html . '</details>';
    }

    /**
     * @param array<string, mixed> $report
     */
    private function renderBaseline(array $report): string
    {
        $baseline = (array) ($report['baseline'] ?? []);
        if ($baseline === [] || ($baseline['used'] ?? false) === false) {
            return '';
        }

        return '<section class="panel"><h2>Baseline</h2><div class="grid four">'
            . $this->mini('Used', ($baseline['used'] ?? false) ? 'yes' : 'no')
            . $this->mini('File', $baseline['file'] ?? '')
            . $this->mini('Ignored', $baseline['ignored'] ?? 0)
            . $this->mini('New', $baseline['new'] ?? 0)
            . $this->mini('Resolved', $baseline['resolved'] ?? 0)
            . '</div></section>';
    }

    /**
     * @param array<string, mixed> $report
     */
    private function renderChangedFiles(array $report): string
    {
        $changed = (array) ($report['changed_files'] ?? []);
        if (($changed['enabled'] ?? false) !== true) {
            return '';
        }

        $html = '<section class="panel"><h2>Changed Files Mode</h2><div class="grid four">'
            . $this->mini('Enabled', 'yes')
            . $this->mini('Base ref', $changed['base_ref'] ?? '')
            . $this->mini('Changed files', $changed['count'] ?? 0)
            . $this->mini('Fallback used', ($changed['fallback_used'] ?? false) ? 'yes' : 'no')
            . $this->mini('Error', $changed['error'] ?? '')
            . '</div>';

        if (($changed['files'] ?? []) !== []) {
            $html .= '<details><summary>Changed files</summary><ul>';
            foreach ((array) $changed['files'] as $file) {
                $html .= '<li><code>' . $this->e($file) . '</code></li>';
            }
            $html .= '</ul></details>';
        }

        return $html . '</section>';
    }

    /**
     * @param array<string, mixed> $report
     */
    private function renderScannerTiming(array $report): string
    {
        $timings = (array) ($report['scanner_timings'] ?? []);
        if ($timings === []) {
            return '';
        }

        $html = '<section class="panel"><h2>Scanner Timing</h2><div class="table-wrap"><table><thead><tr><th>Scanner</th><th>Duration</th></tr></thead><tbody>';
        foreach ($timings as $scanner => $seconds) {
            $html .= '<tr><td>' . $this->e($scanner) . '</td><td>' . $this->e(number_format((float) $seconds, 3)) . 's</td></tr>';
        }

        return $html . '</tbody></table></div></section>';
    }

    private function mini(string $label, mixed $value): string
    {
        return '<div class="mini"><span>' . $this->e($label) . '</span><strong>' . $this->e($value) . '</strong></div>';
    }

    private function css(): string
    {
        return 'body{margin:0;background:#f5f7fb;color:#172033;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.5}.page{max-width:1180px;margin:0 auto;padding:32px 18px}.hero{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;margin-bottom:22px}.eyebrow{text-transform:uppercase;letter-spacing:.08em;color:#4f46e5;font-weight:700;margin:0 0 6px}h1{font-size:32px;margin:0}h2{margin:0 0 14px;font-size:20px}h3{font-size:15px;margin:16px 0 8px}.muted,.meta span,.card span,.mini span{color:#657089}.meta{display:grid;gap:8px;min-width:280px}.meta div,.card,.panel,.mini{background:#fff;border:1px solid #dfe5ef;border-radius:10px;box-shadow:0 1px 2px rgba(20,29,45,.04)}.meta div{padding:10px 12px}.meta span,.meta strong{display:block}.grid{display:grid;gap:14px}.cards{grid-template-columns:repeat(auto-fit,minmax(120px,1fr));margin-bottom:14px}.two{grid-template-columns:repeat(auto-fit,minmax(260px,1fr));margin-bottom:14px}.four{grid-template-columns:repeat(auto-fit,minmax(150px,1fr))}.card{padding:16px}.card strong{display:block;font-size:24px}.card-critical strong,.badge-critical{color:#991b1b}.card-high strong,.badge-high{color:#b45309}.card-medium strong,.badge-medium{color:#92400e}.card-low strong,.badge-low{color:#1d4ed8}.card-info strong,.badge-info{color:#047857}.card-passed strong{color:#047857}.card-warning strong{color:#b45309}.card-failed strong{color:#991b1b}.panel{padding:18px;margin:14px 0}.stack{display:grid;gap:8px}.row{display:flex;justify-content:space-between}.section-title{display:flex;justify-content:space-between;align-items:center}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;border-bottom:1px solid #e7ebf2;padding:10px;vertical-align:top}th{color:#4b5563;background:#f8fafc}.badge{display:inline-block;border-radius:999px;padding:3px 8px;border:1px solid currentColor;font-size:12px;font-weight:700;text-transform:uppercase}.badge-medium{background:#fffbeb}.badge-high{background:#fff7ed}.badge-critical{background:#fef2f2}.badge-low{background:#eff6ff}.badge-info{background:#ecfdf5}.issue{border:1px solid #dfe5ef;border-radius:10px;padding:12px;margin-top:12px;background:#fff}summary{cursor:pointer;font-weight:700}dl{display:grid;grid-template-columns:minmax(140px,220px)1fr;gap:8px 16px}dt{font-weight:700;color:#4b5563}dd{margin:0}pre{background:#111827;color:#f9fafb;border-radius:8px;padding:12px;overflow:auto}code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}.mini{padding:12px}.mini span,.mini strong{display:block;overflow-wrap:anywhere}a{color:#4f46e5}footer{margin:28px 0;color:#657089}@media(max-width:720px){.hero{display:block}.meta{margin-top:16px}dl{grid-template-columns:1fr}.page{padding:20px 12px}}';
    }
}
